ARG UBUNTU_VERSION=24.04
ARG CUDA_VERSION=13.2.0

FROM docker.io/ubuntu:${UBUNTU_VERSION} AS cpu-base

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        bzip2 \
        ca-certificates \
        cmake \
        g++ \
        gcc \
        gdb \
        gfortran \
        git \
        hwloc \
        libconfig-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libfuse-dev \
        libfuse3-dev \
        libhwloc-dev \
        libibverbs-dev \
        libjson-c-dev \
        libnl-3-dev \
        libnuma-dev \
        libsensors-dev \
        libtool \
        libuv1-dev \
        libyaml-dev \
        make \
        numactl \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        rdma-core \
        strace \
        wget \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PMIX_VERSION=4.2.9
RUN wget -q https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.gz \
    && tar xf pmix-${PMIX_VERSION}.tar.gz \
    && cd pmix-${PMIX_VERSION} \
    && ./configure --prefix=/opt/pmix --disable-static \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf pmix-${PMIX_VERSION} pmix-${PMIX_VERSION}.tar.gz

ENV PATH=/opt/pmix/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/pmix/lib:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH=/opt/pmix/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV PMIX_MCA_psec=native

FROM docker.io/nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu${UBUNTU_VERSION} AS gpu-base

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        bzip2 \
        ca-certificates \
        cmake \
        g++ \
        gcc \
        gdb \
        gfortran \
        git \
        hwloc \
        libconfig-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libfuse-dev \
        libfuse3-dev \
        libhwloc-dev \
        libibverbs-dev \
        libjson-c-dev \
        libnl-3-dev \
        libnuma-dev \
        libsensors-dev \
        libtool \
        libuv1-dev \
        libyaml-dev \
        make \
        numactl \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        rdma-core \
        strace \
        wget \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PMIX_VERSION=4.2.9
RUN wget -q https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.gz \
    && tar xf pmix-${PMIX_VERSION}.tar.gz \
    && cd pmix-${PMIX_VERSION} \
    && ./configure --prefix=/opt/pmix --disable-static \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf pmix-${PMIX_VERSION} pmix-${PMIX_VERSION}.tar.gz

ENV PATH=/opt/pmix/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/pmix/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH=/opt/pmix/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV PMIX_MCA_psec=native

FROM cpu-base AS libfabric-cpu

ARG XPMEM_REF=0d0bad4e1d07b38d53ecc8f20786bb1328c446da
RUN git clone https://github.com/hpc/xpmem.git \
    && cd xpmem \
    && git checkout ${XPMEM_REF} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-default-prefix=/usr --disable-kernel-module \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf xpmem

ARG SHS_REF=release/shs-12.0.1
RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cassini-headers.git \
    && cd shs-cassini-headers \
    && cp -r include/* /usr/include/ \
    && cp -r share/* /usr/share/ \
    && cd .. \
    && rm -rf shs-cassini-headers

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cxi-driver.git \
    && cd shs-cxi-driver \
    && cp -r include/* /usr/include/ \
    && cd .. \
    && rm -rf shs-cxi-driver

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-libcxi.git \
    && cd shs-libcxi \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf shs-libcxi

ARG LIBFABRIC_VERSION=2.1.0
RUN git clone --branch v${LIBFABRIC_VERSION} --depth 1 https://github.com/ofiwg/libfabric.git \
    && cd libfabric \
    && ./autogen.sh \
    && ./configure --prefix=/usr --enable-cxi --enable-lnx --enable-efa --enable-xpmem=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf libfabric

ENV FI_PROVIDER=cxi

FROM gpu-base AS libfabric-gpu

ARG XPMEM_REF=0d0bad4e1d07b38d53ecc8f20786bb1328c446da
RUN git clone https://github.com/hpc/xpmem.git \
    && cd xpmem \
    && git checkout ${XPMEM_REF} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-default-prefix=/usr --disable-kernel-module \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf xpmem

ARG GDRCOPY_VERSION=2.5.1
RUN git clone --depth 1 --branch v${GDRCOPY_VERSION} https://github.com/NVIDIA/gdrcopy.git \
    && cd gdrcopy \
    && make CC=gcc CUDA=/usr/local/cuda lib \
    && make lib_install \
    && cd .. \
    && rm -rf gdrcopy

ARG SHS_REF=release/shs-12.0.1
RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cassini-headers.git \
    && cd shs-cassini-headers \
    && cp -r include/* /usr/include/ \
    && cp -r share/* /usr/share/ \
    && cd .. \
    && rm -rf shs-cassini-headers

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cxi-driver.git \
    && cd shs-cxi-driver \
    && cp -r include/* /usr/include/ \
    && cd .. \
    && rm -rf shs-cxi-driver

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-libcxi.git \
    && cd shs-libcxi \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf shs-libcxi

ARG LIBFABRIC_VERSION=2.1.0
RUN git clone --branch v${LIBFABRIC_VERSION} --depth 1 https://github.com/ofiwg/libfabric.git \
    && cd libfabric \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
       --enable-cuda-dlopen --enable-gdrcopy-dlopen --enable-cxi --enable-lnx \
       --enable-efa --enable-xpmem=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf libfabric

ENV FI_PROVIDER=cxi

FROM libfabric-cpu AS ucx-cpu

ARG UCX_VERSION=1.20.0
RUN wget -q https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz \
    && tar xzf ucx-${UCX_VERSION}.tar.gz \
    && cd ucx-${UCX_VERSION} \
    && mkdir build \
    && cd build \
    && ../configure --prefix=/usr --enable-mt --enable-devel-headers \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd ../.. \
    && rm -rf ucx-${UCX_VERSION}.tar.gz ucx-${UCX_VERSION}

FROM libfabric-gpu AS ucx-gpu

ARG UCX_VERSION=1.20.0
RUN wget -q https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz \
    && tar xzf ucx-${UCX_VERSION}.tar.gz \
    && cd ucx-${UCX_VERSION} \
    && mkdir build \
    && cd build \
    && ../configure --prefix=/usr --with-cuda=/usr/local/cuda --with-gdrcopy=/usr/local \
       --enable-mt --enable-devel-headers \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd ../.. \
    && rm -rf ucx-${UCX_VERSION}.tar.gz ucx-${UCX_VERSION}

FROM libfabric-cpu AS mpich-cpu

ARG MPICH_VERSION=4.3.2
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
    && tar xf mpich-${MPICH_VERSION}.tar.gz \
    && cd mpich-${MPICH_VERSION} \
    && ./configure --prefix=/usr --enable-fast=O3,ndebug --enable-fortran --enable-cxx \
       --with-device=ch4:ofi --with-libfabric=/usr --with-xpmem=/usr \
       --with-pmi=pmix --with-pmix=/opt/pmix --with-pm=no \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-${MPICH_VERSION}.tar.gz mpich-${MPICH_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}

FROM libfabric-gpu AS mpich-gpu

ARG MPICH_VERSION=4.3.2
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
    && tar xf mpich-${MPICH_VERSION}.tar.gz \
    && cd mpich-${MPICH_VERSION} \
    && ./configure --prefix=/usr --enable-fast=O3,ndebug --enable-fortran --enable-cxx \
       --with-device=ch4:ofi --with-libfabric=/usr --with-xpmem=/usr \
       --with-pmi=pmix --with-pmix=/opt/pmix --with-pm=no \
       --with-cuda=/usr/local/cuda --with-cuda-sm=80 \
       LIBS="-L/usr/local/cuda/targets/x86_64-linux/lib/stubs -lcuda" \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-${MPICH_VERSION}.tar.gz mpich-${MPICH_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}
ENV MPIR_CVAR_CH4_OFI_ENABLE_HMEM=1

FROM libfabric-cpu AS openmpi-cpu

ARG OPENMPI_VERSION=5.0.8
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OPENMPI_VERSION}.tar.gz \
    && tar xf openmpi-${OPENMPI_VERSION}.tar.gz \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --prefix=/usr --with-ofi=/usr --with-pmix=/opt/pmix \
       --with-hwloc=external --with-libevent=external --without-ucx \
       --disable-oshmem \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openmpi-${OPENMPI_VERSION}.tar.gz openmpi-${OPENMPI_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}
ENV OMPI_MCA_pml=cm
ENV OMPI_MCA_mtl=ofi
ENV PMIX_MCA_psec=native

FROM libfabric-gpu AS openmpi-gpu

ARG OPENMPI_VERSION=5.0.8
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OPENMPI_VERSION}.tar.gz \
    && tar xf openmpi-${OPENMPI_VERSION}.tar.gz \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --prefix=/usr --with-ofi=/usr --with-pmix=/opt/pmix \
       --with-hwloc=external --with-libevent=external --without-ucx \
       --disable-oshmem --with-cuda=/usr/local/cuda \
       --with-cuda-libdir=/usr/local/cuda/targets/x86_64-linux/lib/stubs \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openmpi-${OPENMPI_VERSION}.tar.gz openmpi-${OPENMPI_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}
ENV OMPI_MCA_pml=cm
ENV OMPI_MCA_mtl=ofi
ENV PMIX_MCA_psec=native

FROM ucx-cpu AS openmpi-ofi-ucx-cpu

ARG OPENMPI_VERSION=5.0.8
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OPENMPI_VERSION}.tar.gz \
    && tar xf openmpi-${OPENMPI_VERSION}.tar.gz \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --prefix=/usr --with-ofi=/usr --with-ucx=/usr --with-pmix=/opt/pmix \
       --with-hwloc=external --with-libevent=external --enable-oshmem \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openmpi-${OPENMPI_VERSION}.tar.gz openmpi-${OPENMPI_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}
ENV OMPI_MCA_pml=cm
ENV OMPI_MCA_mtl=ofi
ENV PMIX_MCA_psec=native

FROM ucx-gpu AS openmpi-ofi-ucx-gpu

ARG OPENMPI_VERSION=5.0.8
ARG MPI4PY_VERSION=4.1.0
RUN wget -q https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OPENMPI_VERSION}.tar.gz \
    && tar xf openmpi-${OPENMPI_VERSION}.tar.gz \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --prefix=/usr --with-ofi=/usr --with-ucx=/usr --with-pmix=/opt/pmix \
       --with-hwloc=external --with-libevent=external --enable-oshmem \
       --with-cuda=/usr/local/cuda \
       --with-cuda-libdir=/usr/local/cuda/targets/x86_64-linux/lib/stubs \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openmpi-${OPENMPI_VERSION}.tar.gz openmpi-${OPENMPI_VERSION}
RUN MPICC=mpicc python3 -m pip install --break-system-packages --no-cache-dir --no-binary=mpi4py mpi4py==${MPI4PY_VERSION}
ENV OMPI_MCA_pml=cm
ENV OMPI_MCA_mtl=ofi
ENV PMIX_MCA_psec=native

FROM libfabric-gpu AS nccl-gpu

ARG NCCL_PACKAGE_VERSION=2.29.7-1+cuda13.2
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libnccl2=${NCCL_PACKAGE_VERSION} \
        libnccl-dev=${NCCL_PACKAGE_VERSION} \
    && rm -rf /var/lib/apt/lists/*

ARG AWS_OFI_NCCL_VERSION=1.19.0
RUN wget -q https://github.com/aws/aws-ofi-nccl/releases/download/v${AWS_OFI_NCCL_VERSION}/aws-ofi-nccl-${AWS_OFI_NCCL_VERSION}.tar.gz \
    && tar xf aws-ofi-nccl-${AWS_OFI_NCCL_VERSION}.tar.gz \
    && cd aws-ofi-nccl-${AWS_OFI_NCCL_VERSION} \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda --disable-tests \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf aws-ofi-nccl-${AWS_OFI_NCCL_VERSION}.tar.gz aws-ofi-nccl-${AWS_OFI_NCCL_VERSION}

ARG NCCL_TESTS_VERSION=2.17.1
RUN wget -q -O nccl-tests-${NCCL_TESTS_VERSION}.tar.gz https://github.com/NVIDIA/nccl-tests/archive/refs/tags/v${NCCL_TESTS_VERSION}.tar.gz \
    && tar xf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz \
    && cd nccl-tests-${NCCL_TESTS_VERSION} \
    && make -j$(nproc) MPI=0 NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80" \
    && mkdir -p /opt/nccl-tests \
    && cp -a build /opt/nccl-tests/ \
    && cd .. \
    && rm -rf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz nccl-tests-${NCCL_TESTS_VERSION}

ENV NCCL_NET=AWS\ Libfabric
ENV NCCL_CROSS_NIC=1
ENV NCCL_SOCKET_IFNAME=hsn
ENV NCCL_NET_GDR_LEVEL=PHB
ENV NCCL_NCHANNELS_PER_NET_PEER=4
ENV FI_CXI_DISABLE_HOST_REGISTER=1
ENV FI_MR_CACHE_MONITOR=userfaultfd

FROM nccl-gpu AS nvshmem-gpu

ARG NVSHMEM_PACKAGE_VERSION=3.6.5-1
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libpciaccess0 \
        libnvshmem3-cuda-13=${NVSHMEM_PACKAGE_VERSION} \
        libnvshmem3-dev-cuda-13=${NVSHMEM_PACKAGE_VERSION} \
        libnvshmem3-static-cuda-13=${NVSHMEM_PACKAGE_VERSION} \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /opt/nvshmem /opt/nvshmem-tests \
    && ln -s /usr/bin/nvshmem_13 /opt/nvshmem/bin \
    && ln -s /usr/include/nvshmem_13 /opt/nvshmem/include \
    && ln -s /usr/lib/x86_64-linux-gnu/nvshmem/13 /opt/nvshmem/lib \
    && rm -f /opt/nvshmem/lib/nvshmem_bootstrap_mpi.so* \
       /opt/nvshmem/lib/nvshmem_bootstrap_shmem.so* \
       /opt/nvshmem/lib/nvshmem_transport_ibdevx.so* \
       /opt/nvshmem/lib/nvshmem_transport_ibgda.so* \
       /opt/nvshmem/lib/nvshmem_transport_ibrc.so* \
       /opt/nvshmem/lib/nvshmem_transport_ucx.so*

COPY tests/nvshmem_hello.cu /tmp/nvshmem_hello.cu
RUN nvcc -rdc=true -ccbin g++ -gencode=arch=compute_80,code=sm_80 \
       -I/opt/nvshmem/include /tmp/nvshmem_hello.cu \
       -o /opt/nvshmem-tests/nvshmem_hello \
       -L/opt/nvshmem/lib -lnvshmem_host -lnvshmem_device \
       -Xlinker -rpath -Xlinker /opt/nvshmem/lib \
    && ldconfig \
    && rm -f /tmp/nvshmem_hello.cu

ENV NVSHMEM_HOME=/opt/nvshmem
ENV PATH=/opt/nvshmem/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/nvshmem/lib:${LD_LIBRARY_PATH}
ENV NVSHMEM_BOOTSTRAP=PMI
ENV NVSHMEM_BOOTSTRAP_PMI=PMIX
ENV NVSHMEM_REMOTE_TRANSPORT=libfabric
ENV NVSHMEM_LIBFABRIC_PROVIDER=cxi
ENV NVSHMEM_DISABLE_CUDA_VMM=1
