# Generated by scripts/generate-target-containerfiles.py from container/Containerfile.
# Do not edit directly. Edit the source Containerfile and regenerate.
# Target: gpu-base

ARG UBUNTU_VERSION=24.04
ARG CUDA_VERSION=13.2.0

FROM docker.io/nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu${UBUNTU_VERSION} AS gpu-base

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        bzip2 \
        ca-certificates \
        cmake \
        g++ \
        gcc \
        gdb \
        gfortran \
        git \
        hwloc \
        libconfig-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libfuse-dev \
        libfuse3-dev \
        libhwloc-dev \
        libibverbs-dev \
        libjson-c-dev \
        libnl-3-dev \
        libnuma-dev \
        libsensors-dev \
        libtool \
        libuv1-dev \
        libyaml-dev \
        make \
        numactl \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        rdma-core \
        strace \
        wget \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PMIX_VERSION=4.2.9
RUN wget -q https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.gz \
    && tar xf pmix-${PMIX_VERSION}.tar.gz \
    && cd pmix-${PMIX_VERSION} \
    && ./configure --prefix=/opt/pmix --disable-static \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf pmix-${PMIX_VERSION} pmix-${PMIX_VERSION}.tar.gz

ENV PATH=/opt/pmix/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/pmix/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH=/opt/pmix/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV PMIX_MCA_psec=native

