# Generated by scripts/generate-target-containerfiles.py from container/Containerfile.
# Do not edit directly. Edit the source Containerfile and regenerate.
# Target: libfabric-gpu

ARG UBUNTU_VERSION=24.04
ARG CUDA_VERSION=13.2.0

FROM docker.io/nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu${UBUNTU_VERSION} AS gpu-base

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        bzip2 \
        ca-certificates \
        cmake \
        g++ \
        gcc \
        gdb \
        gfortran \
        git \
        hwloc \
        libconfig-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libfuse-dev \
        libfuse3-dev \
        libhwloc-dev \
        libibverbs-dev \
        libjson-c-dev \
        libnl-3-dev \
        libnuma-dev \
        libsensors-dev \
        libtool \
        libuv1-dev \
        libyaml-dev \
        make \
        numactl \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        rdma-core \
        strace \
        wget \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PMIX_VERSION=4.2.9
RUN wget -q https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.gz \
    && tar xf pmix-${PMIX_VERSION}.tar.gz \
    && cd pmix-${PMIX_VERSION} \
    && ./configure --prefix=/opt/pmix --disable-static \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf pmix-${PMIX_VERSION} pmix-${PMIX_VERSION}.tar.gz

ENV PATH=/opt/pmix/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/pmix/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH=/opt/pmix/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV PMIX_MCA_psec=native

FROM gpu-base AS libfabric-gpu

ARG XPMEM_REF=0d0bad4e1d07b38d53ecc8f20786bb1328c446da
RUN git clone https://github.com/hpc/xpmem.git \
    && cd xpmem \
    && git checkout ${XPMEM_REF} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-default-prefix=/usr --disable-kernel-module \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf xpmem

ARG GDRCOPY_VERSION=2.5.1
RUN git clone --depth 1 --branch v${GDRCOPY_VERSION} https://github.com/NVIDIA/gdrcopy.git \
    && cd gdrcopy \
    && make CC=gcc CUDA=/usr/local/cuda lib \
    && make lib_install \
    && cd .. \
    && rm -rf gdrcopy

ARG SHS_REF=release/shs-12.0.1
RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cassini-headers.git \
    && cd shs-cassini-headers \
    && cp -r include/* /usr/include/ \
    && cp -r share/* /usr/share/ \
    && cd .. \
    && rm -rf shs-cassini-headers

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-cxi-driver.git \
    && cd shs-cxi-driver \
    && cp -r include/* /usr/include/ \
    && cd .. \
    && rm -rf shs-cxi-driver

RUN git clone --branch ${SHS_REF} --depth 1 https://github.com/HewlettPackard/shs-libcxi.git \
    && cd shs-libcxi \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf shs-libcxi

ARG LIBFABRIC_VERSION=2.1.0
RUN git clone --branch v${LIBFABRIC_VERSION} --depth 1 https://github.com/ofiwg/libfabric.git \
    && cd libfabric \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
       --enable-cuda-dlopen --enable-gdrcopy-dlopen --enable-cxi --enable-lnx \
       --enable-efa --enable-xpmem=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf libfabric

ENV FI_PROVIDER=cxi

