#!/usr/bin/env python3
"""Generate one buildable Containerfile per named target stage."""

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = REPO_ROOT / "container" / "Containerfile"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "container" / "targets"
FROM_RE = re.compile(r"^\s*FROM\s+(.+)$", re.IGNORECASE)


class Stage:
    def __init__(self, name, parent, lines):
        self.name = name
        self.parent = parent
        self.lines = lines


def read_text(path):
    with path.open("r") as handle:
        return handle.read()


def write_text(path, content):
    with path.open("w") as handle:
        handle.write(content)


def parse_from(line):
    match = FROM_RE.match(line)
    if not match:
        return None

    tokens = match.group(1).split()
    if not tokens:
        return None

    index = 0
    while index < len(tokens) and tokens[index].startswith("--"):
        index += 1
    if index >= len(tokens):
        return None

    parent = tokens[index]
    stage_name = ""
    for token_index, token in enumerate(tokens):
        if token.lower() == "as" and token_index + 1 < len(tokens):
            stage_name = tokens[token_index + 1]
            break

    if not stage_name:
        raise ValueError("FROM line does not name a stage: {}".format(line.rstrip()))

    return parent, stage_name


def parse_containerfile(path):
    lines = read_text(path).splitlines(keepends=True)
    preamble = []
    stage_order = []
    stages = {}
    current_name = None
    current_parent = ""
    current_lines = []

    for line in lines:
        parsed = parse_from(line)
        if parsed:
            if current_name is not None:
                stages[current_name] = Stage(current_name, current_parent, current_lines)
                stage_order.append(current_name)

            current_parent, current_name = parsed
            current_lines = [line]
            continue

        if current_name is None:
            preamble.append(line)
        else:
            current_lines.append(line)

    if current_name is not None:
        stages[current_name] = Stage(current_name, current_parent, current_lines)
        stage_order.append(current_name)

    if not stages:
        raise ValueError("no named stages found in {}".format(path))

    return preamble, stages, stage_order


def dependency_closure(target, stages):
    if target not in stages:
        raise KeyError(target)

    ordered = []
    seen = set()

    def visit(stage_name):
        if stage_name in seen:
            return
        stage = stages[stage_name]
        if stage.parent in stages:
            visit(stage.parent)
        seen.add(stage_name)
        ordered.append(stage_name)

    visit(target)
    return ordered


def render_target(target, preamble, stages, source):
    source_display = source.relative_to(REPO_ROOT)
    header = [
        "# Generated by scripts/generate-target-containerfiles.py from {}.\n".format(
            source_display
        ),
        "# Do not edit directly. Edit the source Containerfile and regenerate.\n",
        "# Target: {}\n".format(target),
        "\n",
    ]

    output = header + preamble
    if output and output[-1].strip():
        output.append("\n")

    for stage_name in dependency_closure(target, stages):
        if output and output[-1].strip():
            output.append("\n")
        output.extend(stages[stage_name].lines)

    if output and not output[-1].endswith("\n"):
        output[-1] += "\n"
    return "".join(output)


def output_path(output_dir, target):
    return output_dir / "{}.Containerfile".format(target)


def main():
    parser = argparse.ArgumentParser(
        description="Generate buildable per-target Containerfiles from container/Containerfile."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help="source multi-stage Containerfile",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="directory for generated Containerfiles",
    )
    parser.add_argument(
        "--target",
        action="append",
        dest="targets",
        help="target stage to generate; may be specified more than once",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="list named stages in dependency order and exit",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files are up to date without writing",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    output_dir = args.output_dir.resolve()
    preamble, stages, stage_order = parse_containerfile(source)

    if args.list:
        for target in stage_order:
            print(target)
        return 0

    targets = args.targets or stage_order
    unknown = [target for target in targets if target not in stages]
    if unknown:
        print("unknown target(s): {}".format(", ".join(unknown)), file=sys.stderr)
        return 2

    expected = {}
    for target in targets:
        expected[output_path(output_dir, target)] = render_target(
            target, preamble, stages, source
        )

    if args.check:
        stale = []
        for path, expected_content in expected.items():
            if not path.exists():
                stale.append("missing: {}".format(path.relative_to(REPO_ROOT)))
                continue
            if read_text(path) != expected_content:
                stale.append("out of date: {}".format(path.relative_to(REPO_ROOT)))
        if stale:
            print("Generated Containerfiles are not up to date:", file=sys.stderr)
            for item in stale:
                print("  {}".format(item), file=sys.stderr)
            print("Run scripts/generate-target-containerfiles.py", file=sys.stderr)
            return 1
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        write_text(path, content)
        print(path.relative_to(REPO_ROOT))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
